version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  slack: circleci/slack@3.4.2

workflows:
  test_and_notify:
    jobs:
      - maven/test
      - notify:
          requires:
            - maven/test

jobs:
  notify:
    docker:
      - image: cimg/base:2023.03-22.04
    steps:
      - slack/status
